package vn.com.gsoft.thuchi.model.dto;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import vn.com.gsoft.thuchi.model.system.BaseRequest;

import java.math.BigDecimal;
import java.util.Date;

@Data
public class PhieuXuatsReq extends BaseRequest {
    private Integer maPhieuXuat;
    private Long soPhieuXuat;
    private Date ngayXuat;
    private Integer vat;
    private String dienGiai;
    private BigDecimal tongTien;
    private BigDecimal daTra;
    private String nhaThuocMaNhaThuoc;
    private Integer maLoaiXuatNhap;
    private Long khachHangMaKhachHang;
    private Long nhaCungCapMaNhaCungCap;
    private Integer bacSyMaBacSy;
    private Integer userProfileUserId;
    private Date created;
    private Date modified;
    private Boolean active;
    private Boolean isModified;
    private Boolean locked;
    private Boolean isDebt;
    private Date preNoteDate;
    private Integer recordStatusID;
    private String connectivityNoteID;
    private Integer connectivityStatusID;
    private String connectivityResult;
    private Date connectivityDateTime;
    private Integer orderId;
    private BigDecimal discount;
    private BigDecimal score;
    private BigDecimal preScore;
    private Integer archivedId;
    private Integer storeId;
    private Integer targetId;
    private Integer sourceStoreId;
    private Integer targetStoreId;
    private Integer partnerId;
    private Integer prescriptionId;
    private Long uId;
    private String invoiceCode;
    private String invoiceNo;
    private String referenceKey;
    private Date invoiceDate;
    private BigDecimal paymentScore;
    private BigDecimal paymentScoreAmount;
    private Integer bonusPaymentId;
    private String invoiceTemplateCode;
    private String invoiceSeries;
    private String invoiceType;
    private Date archivedDate;
    private BigDecimal prePaymentScore;
    private Integer synStatusId;
    private BigDecimal transPaymentAmount;
    private Integer paymentTypeId;
    private BigDecimal debtPaymentAmount;
    private BigDecimal backPaymentAmount;
    private String linkFile;
    private String doctorComments;
    private String keyNewEInvoice;
    private String keyOldEInvoice;
    private Integer eInvoiceStatusID;
    private Integer signEInvoiceStatusID;
    private Date connEInvoiceDateTime;
    private Date signEInvoiceDateTime;
    private Date destroyEInvoiceDateTime;
    private Date replacedEInvoiceDateTime;
    private Date editedEInvoiceDateTime;
    private String kHHDon;
    private String kHMSHDon;
    private String sHDon;
    private Integer pickUpOrderId;
    private String eSampleNoteCode;
    private String linkConfirm;
    private String taxAuthorityCode;
    private String eInvoiveResult;
    private Boolean isRefSampleNote;
    private Date nextPurchaseDate;
    private String trackingIdZNS;
    private String resultZNS;
    private Integer idPaymentQR;
    private Integer targetManagementId;
}

